version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 1002:5000
  sync:
    profiles: ["skiller-whale"]
    image: "ghcr.io/skiller-whale/learnersync:0.2.4"
    network_mode: "host"
    environment:
      SERVER_URL: https://train.skillerwhale.com
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: ".py .yaml .json .css .html .md .chat"
      IGNORE_MATCH: ".git"
    volumes:
      - .:/app/exercises
      - ./.chat_history:/app/chat_history
      - ./attendance_id:/app/sync/attendance_id
    tty: true
    stdin_open: true
  continue_session_sync_filter:
    profiles: ["skiller-whale"]
    image: "ghcr.io/skiller-whale/continue-session-sync-filter:0.0.2"
    volumes:
      - /home/learner/.continue/sessions:/sessions_raw
      - /home/learner/genai-coding-with-llms/.chat_history:/sessions_filtered
  indexing_provider:
    profiles: ["skiller-whale"]
    build: .codebase_indexing
    volumes:
      - ./src:/codebase
      - ./attendance_id:/app/sync/attendance_id
    ports:
      - "5001:5001"
